unit = {declaration};


declaration
	= namespaceDeclaration
	| typeDeclaration
	| enumDeclaration
	| letDeclaration
	| methodDeclaration
	;

namespaceDeclaration = "namespace" IDENTIFIER "{" {declaration} "}";

typeDeclaration = "type" IDENTIFIER "{" letDeclaration "}";

enumDeclaration = "enum" IDENTIFIER "{" [enumMember {"," enumMember} ] "}";

enumMember = IDENTIFIER ["(" IDENTIFIER ")"];

letDeclaration = "let" IDENTIFIER [":" ["const"] IDENTIFIER] ["=" (LITERAL | IDENTIFIER | expresion)];

methodDeclaration = "fn" IDENTIFIER "(" [parameter {"," parameter}] ")" [IDENTIFIER] "{" [statement] "}";

scope = statement | "{" {statement} "}";

statement
	= declaration
	| ("if" expresion statement ["else" statement])
	| ("match" expresion "{" {(IDENTIFIER | expresion) "->" scope} [(UNDERSCORE) "->" scope] "}")
	| scope
	;

expresion = binary {operatorLow binary};

binary = [("-" | "!")] value [operatorHight binary];

value = LITERAL | ("(" expresion ")");

operatorLow
	= "==" | "!=" | "<" | "<=" | ">" | ">="
	| "&" | "|" | "~" | "^" | "<<" | ">>"
	| "+" | "-";

operatorHight = "*" | "/";
